backend:
  name: git-gateway
  repo: https://github.com/cameron-yee/gatsby
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow
display_url: https://mndship.netlify.com

collections:
    - name: cameron-content
      label: Cameron Content
      folder: src/data/cameron
      create: true
      fields:
          - { name: slug, label: Slug, widget: string }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: alt, label: Alt, widget: string }
          - { name: type,  label: Type, widget: select, options: ['Personal', 'DSHIP'] }
          - { name: person, label: Person, widget: hidden, default: cameron }
          - { name: body, label: Body, widget: markdown }

    - name: eric-content
      label: Eric Content
      folder: src/data/eric
      create: true
      fields:
          - { name: slug, label: Slug, widget: string }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: alt, label: Alt, widget: string }
          - { name: type,  label: Type, widget: select, options: ['Personal', 'DSHIP'] }
          - { name: person, label: Person, widget: hidden, default: eric }
          - { name: body, label: Body, widget: markdown }

    - name: eric-book
      label: Eric Book
      folder: src/data/eric/books
      create: true
      fields:
          - { name: slug, label: Slug, widget: string }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: alt, label: Alt, widget: string }
          - { name: type,  label: Type, widget: hidden, default: book }
          - { name: author, label: Author(s), widget: string, default: eric }
          - { name: description, label: Description, widget: text }
          - { name: genre, label: Genre, widget: select, multiple: true, options: ['Action','Biography','Comic Book','Comedy','Drama','Educational','Easy Reading','Fantasy','Fun','History','Horror','Mystery','Non-fiction','Poetry','Sci-fi','Short Story','Thriller'] }
          - { name: year, label: Year, widget: string, required: false }
          - { name: buyingLink, label: Buying Link, widget: string, required: false }
          - { name: person, label: Person, widget: hidden, default: eric }

    - name: cameron-book
      label: Cameron Book
      folder: src/data/cameron/books
      create: true
      fields:
          - { name: slug, label: Slug, widget: string }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: alt, label: Alt, widget: string }
          - { name: type,  label: Type, widget: hidden, default: book }
          - { name: author, label: Author(s), widget: string, default: cameron }
          - { name: description, label: Description, widget: text }
          - { name: genre, label: Genre, widget: select, multiple: true, options: ['Action','Biography','Comic Book','Comedy','Drama','Fantasy','History','Horror','Mystery','Non-fiction','Poetry','Sci-fi','Short Story','Thriller'] }
          - { name: year, label: Year, widget: string, required: false }
          - { name: buyingLink, label: Buying Link, widget: string, required: false }
          - { name: person, label: Person, widget: hidden, default: cameron }
    
    # - name: sleep
    #   label: Sleep
    #   folder: src/pages/markdown/sleep
    #   create: true
    #   fields:
    #       - { name: path, label: Path }
    #       - { name: fname, label: "First Name", widget: string }
    #       - { name: lname, label: "Last Name", widget: string }
    #       - { name: date, label: Date, widget: date }
    #       - { name: bed_time, label: "Bed Time", widget: string }
    #       - { name: wake_up_time, label: "Wake Up Time", widget: string }
    #       - { name: notes, label: "Notes", widget: text }

