backend:
  name: git-gateway
  repo: https://github.com/cameron-yee/gatsby
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: assets

collections:
    - name: blog
      label: Blog
      folder: src/pages/markdown/blog
      create: true
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
    
    - name: sleep
      label: Sleep
      folder: src/pages/markdown/sleep
      create: true
      fields:
          - { name: path, label: Path }
          - { name: fname, label: "First Name", widget: string }
          - { name: lname, label: "Last Name", widget: string }
          - { name: date, label: Date, widget: date }
          - { name: bed_time, label: "Bed Time", widget: string }
          - { name: wake_up_time, label: "Wake Up Time", widget: string }
          - { name: notes, label: "Notes", widget: text }

